// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAssignment_3_BookTrack.Data.Context;

namespace WebAssignment_3_BookTrack.Migrations.Category
{
    [DbContext(typeof(CategoryContext))]
    [Migration("20210803023927_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("WebAssignment_3_BookTrack.Data.Category", b =>
                {
                    b.Property<string>("NameToken")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("NameToken");

                    b.ToTable("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
